
//n = number
//a = alphanumeric
//c = number or alphanumeric

export default {
    "AD":{"country":"Andorra","bank":"4n 4n","account":"12c"},
    "AL":{"country":"Albania","bank":"8n","account":"16c"},
    "AT":{"country":"Austria","bank":"5n","account":"11n"},
    "BA":{"country":"Bosnia and Herzegovina","bank":"3n 3n","account":"8n 2n"},
    "BE":{"country":"Belgium","bank":"3n","account":"7n 2n"},
    "BG":{"country":"Bulgaria","bank":"4a 4n","account":"2n 8c"},
    "CH":{"country":"Switzerland","bank":"5n","account":"12c"},
    "CY":{"country":"Cyprus","bank":"3n 5n","account":"16c"},
    "CZ":{"country":"Czech Republic","bank":"4n","account":"16n"},
    "DE":{"country":"Germany","bank":"8n","account":"10n"},
    "DK":{"country":"Denmark","bank":"4n","account":"9n 1n"},
    "EE":{"country":"Estonia","bank":"2n","account":"2n 11n 1n"},
    "ES":{"country":"Spain","bank":"4n 4n","account":"2n 10n"},
    "FI":{"country":"Finland","bank":"6n","account":"7n 1n"},
    "FO":{"country":"Faroe Islands","bank":"4n","account":"9n 1n"},
    "FR":{"country":"France","bank":"5n 5n","account":"11c 2n"},
    "GB":{"country":"United Kingdom","bank":"4a 6n","account":"8n"},
    "GE":{"country":"Georgia","bank":"2a","account":"16n"},
    "GI":{"country":"Gibraltar","bank":"4a","account":"15c"},
    "GL":{"country":"Greenland","bank":"4n","account":"9n 1n"},
    "GR":{"country":"Greece","bank":"3n 4n","account":"16c"},
    "HR":{"country":"Croatia","bank":"7n","account":"10n"},
    "HU":{"country":"Hungary","bank":"3n 4n","account":"1n 15n 1n"},
    "IE":{"country":"Ireland","bank":"4a 6n","account":"8n"},
    "IL":{"country":"Israel","bank":"3n 3n","account":"13n"},
    "IS":{"country":"Iceland","bank":"4n","account":"2n 16n"},
    "IT":{"country":"Italy","bank":"1a 5n 5n","account":"12c"},
    "KW":{"country":"Kuwait","bank":"4a","account":"22c"},
    "KZ":{"country":"Kazakhstan","bank":"3n","account":"13c"},
    "LB":{"country":"Lebanon","bank":"4n","account":"20c"},
    "LI":{"country":"Liechtenstein","bank":"5n","account":"12c"},
    "LT":{"country":"Lithuania","bank":"5n","account":"11n"},
    "LU":{"country":"Luxembourg","bank":"3n","account":"13c"},
    "LV":{"country":"Latvia","bank":"4a","account":"13c"},
    "MC":{"country":"Monaco","bank":"5n 5n","account":"11c 2n"},
    "ME":{"country":"Montenegro","bank":"3n","account":"13n 2n"},
    "MK":{"country":"Macedonia","bank":"3n","account":"10c 2n"},
    "MR":{"country":"Mauritania","bank":"5n 5n","account":"11n 2n"},
    "MT":{"country":"Malta","bank":"4a 5n","account":"18c"},
    "MU":{"country":"Mauritius","bank":"4a 4n","account":"15n 3a"},
    "NL":{"country":"Netherlands","bank":"4a","account":"10n"},
    "NO":{"country":"Norway","bank":"4n","account":"6n 1n"},
    "PL":{"country":"Poland","bank":"8n","account":"16n"},
    "PT":{"country":"Portugal","bank":"4n 4n","account":"11n 2n"},
    "RO":{"country":"Romania","bank":"4a","account":"16c"},
    "RS":{"country":"Serbia","bank":"3n","account":"13n 2n"},
    "SA":{"country":"Saudi Arabia","bank":"2n","account":"18c"},
    "SE":{"country":"Sweden","bank":"3n","account":"16n 1n"},
    "SI":{"country":"Slovenia","bank":"5n","account":"8n 2n"},
    "SK":{"country":"Slovak Republic","bank":"4n","account":"16n"},
    "SM":{"country":"San Marino","bank":"1a 5n 5n","account":"12c"},
    "TN":{"country":"Tunisia","bank":"2n 3n","account":"13n 2n"},
    "TR":{"country":"Turkey","bank":"5n","account":"1c 16c"}
}